// src/components/PredictionForm.jsx
import React, { useState, useRef } from "react";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import {
  Car,
  Globe,
  ArrowRight,
  FileText,
  Share2,
  Copy,
  CheckCircle,
} from "lucide-react";
import toast from "react-hot-toast";

/**
 * PredictionForm.jsx
 * Option D - Futuristic Neon Electric Car design
 *
 * Behavior summary:
 * - Form appears initially
 * - On submit: form hides -> spinner (green-world) shows -> results card appears
 * - Background: neon car drives left->right with glowing digital CO2 particles
 * - Icons use lucide-react
 * - Responsive (mobile-first)
 */

// API URL: from Vite .env (VITE_API_URL) or fall back to localhost
const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

export default function PredictionFormA() {
  // Form state (controlled inputs)
  const [form, setForm] = useState({
    fuel_type: "",
    cylinders: "",
    engine_size: "",
  });

  // loading true => spinner visible
  const [loading, setLoading] = useState(false);
  // prediction holds API response object or null
  const [prediction, setPrediction] = useState(null);
  // to disable repeated submissions
  const [disabled, setDisabled] = useState(false);
  // ref to result card so we can open a print window/PDF
  const resultRef = useRef(null);

  // update state for inputs
  function handleChange(e) {
    setForm((p) => ({ ...p, [e.target.name]: e.target.value }));
  }

  // Prepare the printable HTML (opens new window) — used for "Save as PDF / Print"
  function printResult(predObj) {
    const html = `
      <html>
        <head>
          <title>CO₂ Emission Prediction</title>
          <meta name="viewport" content="width=device-width,initial-scale=1" />
          <style>
            body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; padding: 24px; color: #111; }
            .card { max-width: 720px; margin: 0 auto; border-radius: 12px; padding: 20px; border: 1px solid #e6e6e6; }
            .h1 { font-size: 20px; font-weight: 700; margin-bottom: 8px; }
            .p { margin-bottom: 6px; }
            .note { margin-top: 12px; color: #444; font-size: 13px; }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="h1">CO₂ Emission Prediction</div>
            <div class="p"><strong>Fuel type:</strong> ${predObj.fuel_type}</div>
            <div class="p"><strong>Cylinders:</strong> ${predObj.cylinders}</div>
            <div class="p"><strong>Engine size (L):</strong> ${predObj.engine_size}</div>
            <hr/>
            <div class="p"><strong>Estimated CO₂ (g/km):</strong> ${predObj.prediction}</div>
            <div class="note">Generated by CO₂ Emissions Predictor • Use "Print" in your browser to save as PDF.</div>
          </div>
        </body>
      </html>
    `;
    const w = window.open("", "_blank", "width=800,height=800");
    if (!w) {
      toast.error("Unable to open print window (popups blocked).");
      return;
    }
    w.document.open();
    w.document.write(html);
    w.document.close();
    // give the new window a moment to finish layout, then call print
    setTimeout(() => w.print(), 500);
  }

  // copy textual summary to clipboard
  async function copyResultToClipboard(predObj) {
    const text = `CO2 prediction: ${predObj.prediction} g/km\nFuel: ${predObj.fuel_type}\nCylinders: ${predObj.cylinders}\nEngine size: ${predObj.engine_size} L`;
    try {
      await navigator.clipboard.writeText(text);
      toast.success("Result copied to clipboard");
    } catch {
      toast.error("Copy failed — try manually selecting the result");
    }
  }

  // attempt to use Web Share API (for mobile) — fallback to copy
  async function shareResult(predObj) {
    const shareText = {
      title: "CO₂ Emission Prediction",
      text: `Estimated CO₂: ${predObj.prediction} g/km\nFuel: ${predObj.fuel_type}\nCylinders: ${predObj.cylinders}\nEngine size: ${predObj.engine_size} L`,
    };
    if (navigator.share) {
      try {
        await navigator.share(shareText);
        toast.success("Shared!");
      } catch {
        toast.error("Share cancelled or failed");
      }
    } else {
      copyResultToClipboard(predObj);
    }
  }

  // main submit handler
  async function handleSubmit(e) {
    e.preventDefault();

    // basic validation
    if (!form.fuel_type || !form.cylinders || !form.engine_size) {
      toast.error("Please fill all fields");
      return;
    }

    // disable UI while request in flight
    setDisabled(true);
    setLoading(true);
    setPrediction(null);
    toast.dismiss();

    // payload with numeric conversions
    const payload = {
      fuel_type: form.fuel_type,
      cylinders: parseInt(form.cylinders, 10),
      engine_size: parseFloat(form.engine_size),
    };

    try {
      // ensure spinner shows at least 700ms for perceived responsiveness
      const minSpinner = new Promise((res) => setTimeout(res, 700));

      // POST request to backend
      const res = await axios.post(`${API_URL}/predict/`, payload, {
        timeout: 12_000,
      });

      // Wait for both network and the min spinner to finish
      await minSpinner;

      // normalize response: accept multiple possible shapes
      const val =
        res.data.predicted_CO2 ??
        res.data.predicted_co2 ??
        res.data.co2_emissions ??
        res.data.predicted_CO2_Emission ??
        res.data.predicted;

      if (val === undefined) {
        throw new Error("Unexpected response from server");
      }

      // format to 2 decimals
      const predStr = Number(val).toFixed(2);

      // store prediction plus metadata for result UI
      const predObj = {
        prediction: predStr,
        fuel_type: payload.fuel_type,
        cylinders: payload.cylinders,
        engine_size: payload.engine_size,
      };

      setPrediction(predObj);
      toast.success("Prediction ready", { icon: <CheckCircle /> });
    } catch (err) {
      console.error(err);
      const msg =
        err?.response?.data?.detail ||
        err?.message ||
        "Prediction failed — check backend or inputs";
      toast.error(msg);
    } finally {
      setLoading(false);
      setDisabled(false);
    }
  }

  // Render starts here
  return (
    <div className="min-h-screen relative overflow-hidden bg-gradient-to-br from-[#030712] via-[#071028] to-[#04051a]">
      {/* ---------------------------
          BACKGROUND: Neon futuristic car + digital CO2 particles
         --------------------------- */}
      <div className="absolute inset-0 pointer-events-none -z-10">
        {/* moving neon car (framer motion) */}
        <motion.div
          initial={{ x: "-120%" }}
          animate={{ x: "120%" }}
          transition={{ repeat: Infinity, duration: 18, ease: "linear" }}
          className="absolute top-1/3 left-0"
        >
          {/* Neon car SVG silhouette */}
          <svg
            width="260"
            height="120"
            viewBox="0 0 260 120"
            xmlns="http://www.w3.org/2000/svg"
          >
            <defs>
              <linearGradient id="neon" x1="0" x2="1">
                <stop offset="0" stopColor="#00F5A0" />
                <stop offset="0.6" stopColor="#06B6D4" />
                <stop offset="1" stopColor="#7C3AED" />
              </linearGradient>
              <filter id="glow">
                <feGaussianBlur stdDeviation="6" result="coloredBlur" />
                <feMerge>
                  <feMergeNode in="coloredBlur" />
                  <feMergeNode in="SourceGraphic" />
                </feMerge>
              </filter>
            </defs>

            {/* Car body (neon outline) */}
            <g filter="url(#glow)" transform="translate(0,0)">
              <path
                d="M20 70 L40 45 L90 35 L170 35 L210 55 L240 60 L250 60 L250 75 L20 75 Z"
                fill="none"
                stroke="url(#neon)"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
                opacity="0.95"
              />
              {/* wheels as neon rings */}
              <circle cx="70" cy="78" r="12" stroke="#06B6D4" strokeWidth="2" fill="none" />
              <circle cx="200" cy="78" r="12" stroke="#06B6D4" strokeWidth="2" fill="none" />
            </g>
          </svg>

          {/* DIGITAL CO2 PARTICLES (map to create many glowing dots) */}
          <div className="relative -mt-12">
            {[...Array(18)].map((_, i) => (
              <motion.div
                key={`dot-${i}`}
                initial={{ x: 20 + i * 6, y: 10, opacity: 0 }}
                animate={{
                  x: [-20 - i * 6, -60 - i * 20],
                  y: [-6 - (i % 3) * 4, -26 - (i % 4) * 6],
                  opacity: [0, 0.9, 0.1],
                  scale: [0.3, 1.1, 1.6],
                }}
                transition={{
                  duration: 2.4 + (i % 5) * 0.15,
                  repeat: Infinity,
                  ease: "easeOut",
                  delay: i * 0.08,
                }}
                className="absolute"
                style={{ left: `${i * 8}px` }}
              >
                <div
                  className="w-4 h-4 rounded-full blur-sm"
                  style={{
                    background: `rgba(${10 + i * 8}, ${220 - i * 8}, ${255 - i * 4}, 0.85)`,
                    boxShadow: `0 6px 18px rgba(6, 182, 212, 0.35)`,
                  }}
                />
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* ---------------------------
          MAIN CONTENT: Centered form | spinner | result
         --------------------------- */}
      <div className="relative z-10 flex items-center justify-center min-h-screen p-6">
        <AnimatePresence mode="wait">
          {/* ----- LOADING (spinner) ----- */}
          {loading ? (
            <motion.div
              key="spinner"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.28 }}
              className="flex flex-col items-center gap-4"
            >
              {/* Green world spinner */}
              <div className="w-40 h-40 rounded-full bg-gradient-to-br from-emerald-400 to-green-600 flex items-center justify-center shadow-2xl">
                <div className="w-28 h-28 rounded-full bg-white/8 flex items-center justify-center border border-white/10">
                  <Globe className="w-14 h-14 text-white/90 animate-pulse" />
                </div>
              </div>

              {/* message */}
              <div className="text-center">
                <div className="text-white font-semibold">Securing a safer planet...</div>
                <div className="text-sm text-gray-300">Calculating your vehicle’s CO₂ footprint</div>
              </div>
            </motion.div>

          // ----- RESULT CARD -----
          ) : prediction ? (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.36 }}
              className="w-full max-w-xl"
              ref={resultRef}
            >
              {/* result card */}
              <div className="bg-gradient-to-br from-white/6 to-white/3 backdrop-blur-md border border-white/10 rounded-2xl p-6 shadow-2xl">
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <div className="w-14 h-14 rounded-lg bg-gradient-to-br from-green-400 to-emerald-500 flex items-center justify-center shadow-md">
                      <Car className="w-7 h-7 text-white" />
                    </div>
                  </div>

                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-sm text-gray-300">Estimated CO₂</div>
                        <div className="text-2xl font-bold text-white">
                          {prediction.prediction} <span className="text-sm font-medium text-gray-300">g/km</span>
                        </div>
                      </div>

                      <div className="text-right text-xs text-gray-400">
                        <div>Based on:</div>
                        <div className="font-medium text-white">{prediction.fuel_type} • {prediction.cylinders} cyl</div>
                        <div className="text-gray-300">{prediction.engine_size} L</div>
                      </div>
                    </div>

                    {/* explanatory paragraph */}
                    <p className="mt-4 text-sm text-gray-200">
                      This is an estimate based on engine size, cylinders and fuel type.
                      A lower number is better — consider reducing engine load, switching to cleaner fuel, or more efficient driving to lower emissions.
                    </p>

                    {/* actionable suggestions */}
                    <ul className="mt-3 text-sm text-gray-300 space-y-2">
                      <li>• Keep tires properly inflated and maintain regular servicing.</li>
                      <li>• Avoid idling; combine trips and drive smoothly to reduce emissions.</li>
                      <li>• If possible, consider hybrid/electric alternatives or cleaner fuels.</li>
                    </ul>

                    {/* action buttons */}
                    <div className="mt-5 flex flex-wrap gap-3">
                      <button
                        onClick={() => printResult(prediction)}
                        className="inline-flex items-center gap-2 bg-white/8 hover:bg-white/12 text-white px-3 py-2 rounded-md text-sm border border-white/10"
                      >
                        <FileText className="w-4 h-4" /> Print / Save PDF
                      </button>

                      <button
                        onClick={() => shareResult(prediction)}
                        className="inline-flex items-center gap-2 bg-white/8 hover:bg-white/12 text-white px-3 py-2 rounded-md text-sm border border-white/10"
                      >
                        <Share2 className="w-4 h-4" /> Share
                      </button>

                      <button
                        onClick={() => copyResultToClipboard(prediction)}
                        className="inline-flex items-center gap-2 bg-white/8 hover:bg-white/12 text-white px-3 py-2 rounded-md text-sm border border-white/10"
                      >
                        <Copy className="w-4 h-4" /> Copy
                      </button>

                      <button
                        onClick={() => {
                          setPrediction(null);
                          setForm({ fuel_type: "", cylinders: "", engine_size: "" });
                        }}
                        className="ml-auto inline-flex items-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-white px-3 py-2 rounded-md font-medium text-sm"
                      >
                        <ArrowRight className="w-4 h-4" /> New Prediction
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

          // ----- DEFAULT: SHOW FORM -----
          ) : (
            <motion.div
              key="form"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.98 }}
              transition={{ duration: 0.28 }}
              className="w-full max-w-md"
            >
              {/* Form container */}
              <div className="bg-gradient-to-br from-white/3 to-white/6 backdrop-blur-md rounded-2xl p-6 shadow-2xl border border-white/8">
                {/* header */}
                <div className="text-center mb-4">
                  <div className="mx-auto w-14 h-14 rounded-lg bg-gradient-to-br from-[#00F5A0] to-[#7C3AED] flex items-center justify-center">
                    <Car className="w-7 h-7 text-black/90" />
                  </div>
                  <h2 className="mt-3 text-xl font-bold text-white">CO₂ Emissions Predictor</h2>
                  <p className="text-sm text-gray-300 mt-1">Enter vehicle info to estimate emissions</p>
                </div>

                {/* the form element */}
                <form onSubmit={handleSubmit} className="space-y-4">
                  {/* fuel type */}
                  <div>
                    <label className="block text-sm text-gray-200 mb-2">Fuel Type</label>
                    <select
                      name="fuel_type"
                      value={form.fuel_type}
                      onChange={handleChange}
                      required
                      className="w-full p-3 rounded-lg bg-transparent border border-white/10 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#00F5A0]"
                    >
                      <option value="">Choose fuel type</option>
                      {/* dataset categories are X, Z, E, D, N */}
                      <option value="X">X - Regular Gasoline</option>
                      <option value="Z">Z - Premium Gasoline</option>
                      <option value="E">E - Ethanol</option>
                      <option value="D">D - Diesel</option>
                      <option value="N">N - Natural Gas</option>
                    </select>
                  </div>

                  {/* cylinders */}
                  <div>
                    <label className="block text-sm text-gray-200 mb-2">Cylinders</label>
                    <input
                      name="cylinders"
                      value={form.cylinders}
                      onChange={handleChange}
                      required
                      type="number"
                      min="2"
                      max="16"
                      className="w-full p-3 rounded-lg bg-transparent border border-white/10 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#06B6D4]"
                      placeholder="e.g. 4"
                    />
                  </div>

                  {/* engine size */}
                  <div>
                    <label className="block text-sm text-gray-200 mb-2">Engine size (L)</label>
                    <input
                      name="engine_size"
                      value={form.engine_size}
                      onChange={handleChange}
                      required
                      type="number"
                      step="0.1"
                      min="0.1"
                      max="10"
                      className="w-full p-3 rounded-lg bg-transparent border border-white/10 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#7C3AED]"
                      placeholder="e.g. 2.0"
                    />
                  </div>

                  {/* submit */}
                  <button
                    type="submit"
                    disabled={disabled}
                    className="w-full mt-2 inline-flex items-center justify-center gap-3 bg-gradient-to-r from-[#00F5A0] to-[#7C3AED] text-black font-semibold py-3 rounded-lg shadow-xl hover:brightness-110 disabled:opacity-60"
                  >
                    <span>Predict CO₂</span>
                    <ArrowRight className="w-4 h-4" />
                  </button>
                </form>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
